# Generated by Django 4.2.20 on 2025-04-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_question_text_required_if_yes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='answer',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
